# fly.toml app configuration file generated for remix-saas-starter on 2024-10-11T11:09:45-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'remix-saas-starter'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
